apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
  {{- include "postgres.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.database.username | quote }}
  POSTGRES_DB: {{ .Values.database.databaseName | quote }}
