{{- if not .Values.password.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ randAlphaNum 64 | b64enc | quote }}
{{- end -}}
