apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control-plane.fullname" . }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY_BASE: {{ randAlphaNum 16 }}
