apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "control-plane.fullname" . }}-worker
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "control-plane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "control-plane.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "control-plane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "control-plane.fullname" . }}
            - secretRef:
                name: {{ include "control-plane.fullname" . }}
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: {{ .Release.Name }}-postgres
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: {{ .Release.Name }}-postgres
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: {{ .Release.Name }}-postgres
          args:
            - sidekiq
          resources:
            {{- toYaml .Values.resourcesWorker | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
